name: CI/CD Terraform Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Init
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: init
          directory: ./

      - name: Terraform Validate
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: validate
          directory: ./

      - name: Terraform Plan
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: plan
          directory: ./

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: robertdebock/terraform-action@1.1.4
        with:
          action: apply
          directory: ./
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
